name: aeson-qq
version: 0.8.3
synopsis: JSON quasiquoter for Haskell
description: |
  @aeson-qq@ provides a JSON quasiquoter for Haskell.

  This package exposes the function `aesonQQ` that compile-time
  converts a string representation of a JSON value into a
  `Data.Aeson.Value`.  `aesonQQ` has the signature

  >aesonQQ :: QuasiQuoter

  Consult the @README@ for documentation:
  <https://github.com/sol/aeson-qq#readme>

category: JSON
author: Oscar Finnsson
maintainer: Simon Hengel <sol@typeful.net>
license: MIT

github: sol/aeson-qq

ghc-options: -Wall

dependencies:
  - base >= 4.5 && < 5
  - base-compat
  - text
  - attoparsec
  - scientific
  - vector
  - aeson >= 0.6
  - parsec
  - template-haskell
  - haskell-src-meta >= 0.1.0

source-dirs: src

library:
  exposed-modules:
    - Data.Aeson.QQ

tests:
  spec:
    main: Spec.hs
    source-dirs:
      - test
    dependencies:
      - hspec
      - ghc-prim # Needed for GHC 7.4.*
    build-tools:
      - hspec-discover
